// @vitest-environment jsdom
import {act,createElement,useState} from 'react'
import {createRoot,type Root} from 'react-dom/client'
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest'
import type {TrackRecord} from '../src/protocol.ts'
import type {ResourceAsset} from '../src/track/resources.ts'
import {editedMetrics} from '../src/track/edit.ts'
import {TrackPanel} from '../src/client/TrackPanel.tsx'
import {ResourceUseDialog,appendedResourcePhotos} from '../src/client/ResourceUseDialog.tsx'
import {VideoResourceImagePicker} from '../src/client/VideoResourceImagePicker.tsx'
import {VideoResourceSelections} from '../src/client/VideoResourceSelections.tsx'
import {loadResourceLibrary} from '../src/client/resources-api.ts'

const mocks=vi.hoisted(()=>({track:null as TrackRecord|null,refreshToken:0,initialIds:undefined as string[]|undefined,restored:undefined as any,initialAssetUrl:undefined as string|undefined,update:vi.fn(),retry:vi.fn()}))
vi.mock('../src/client/useTracks.ts',()=>({useTracks:()=>({open:mocks.track,list:[],error:'',note:'',refresh:vi.fn(),closeTrack:vi.fn(),clearError:vi.fn()})}))
vi.mock('../src/client/map-settings.tsx',()=>({MapSettingsProvider:({children}:{children:unknown})=>children,useMapSettings:()=>({settings:{basemap:'none'},updateSettings:vi.fn(),openSettings:vi.fn()})}))
vi.mock('../src/client/useTrackAgentDrawer.ts',()=>({useTrackAgentDrawer:()=>({available:false,toggle:vi.fn()})}))
vi.mock('../src/client/TrackEditor.tsx',()=>({TrackEditor:()=>null}))
vi.mock('../src/client/AnimationStudio.tsx',()=>({AnimationStudio:()=>null}))
vi.mock('../src/client/TrackVideoScript.tsx',()=>({TrackVideoScript:({onCancel}:{onCancel:()=>void})=>createElement('button',{onClick:onCancel},'返回资源库视频')}))
vi.mock('../src/client/TrackOverview.tsx',()=>({TrackOverview:({onPhotoAI,refreshToken}:{onPhotoAI:(url:string)=>void;refreshToken:number})=>{const [selected,setSelected]=useState(false);mocks.refreshToken=refreshToken;return createElement('div',{'data-testid':'overview'},createElement('button',{onClick:()=>setSelected(true)},selected?'已选点位':'选择点位'),createElement('button',{onClick:()=>onPhotoAI('https://example.com/photo.jpg')},'美化原照片'))}}))
vi.mock('../src/client/ResourceLibrary.tsx',()=>({ResourceLibrary:({onBack,onVideo,onCreate,onHistory}:any)=>createElement('section',{'aria-label':'独立资源页'},createElement('button',{onClick:onBack},'返回轨迹'),createElement('button',{onClick:onVideo},'进入视频'),createElement('button',{onClick:()=>onCreate(['photo'])},'选择图片创作'),createElement('button',{onClick:onHistory},'资源历史'))}))
vi.mock('../src/client/ResourceImageWorkspace.tsx',()=>({ResourceImageWorkspace:({onBack,onHistory,onVideo,initialAssetUrl,initialAssetIds,restore}:any)=>{const [draft,setDraft]=useState('');mocks.initialAssetUrl=initialAssetUrl;mocks.initialIds=initialAssetIds;mocks.restored=restore;return createElement('section',{'aria-label':'独立创作页'},createElement('button',{onClick:onBack},'返回素材管理'),createElement('button',{onClick:onHistory},'创作历史'),createElement('button',{onClick:onVideo},'进入创作视频'),createElement('button',{onClick:()=>setDraft('已填写草稿')},draft||'填写草稿'))}}))
vi.mock('../src/client/ResourceImageHistory.tsx',()=>({ResourceImageHistory:({onBack,onRestore}:any)=>createElement('section',{'aria-label':'历史任务页'},createElement('button',{onClick:onBack},'返回历史来源'),createElement('button',{onClick:()=>onRestore({id:'job',prompt:'原始提示词'},'result')},'点击生成图恢复'))}))
vi.mock('../src/client/useTrackPlacemarks.ts',()=>({useTrackPlacemarks:()=>({points:[{id:'point',name:'山顶',images:['https://example.com/original.jpg']}],loading:false,editReady:true,updatePoint:mocks.update,retry:mocks.retry})}))
vi.mock('../src/client/resources-api.ts',()=>({loadResourceLibrary:vi.fn()}))
const coordinates:TrackRecord['coordinates']=[[114,27,100,1000],[114.1,27.1,200,2000]]
const track:TrackRecord={id:'resource-ui',name:'山地路线',filename:'route.gpx',format:'gpx',createdAt:'2026-10-05',points:2,bytes:100,coordinates,metrics:editedMetrics(coordinates)}
const asset:ResourceAsset={id:'photo',trackId:track.id,name:'AI 结果',kind:'image',mime:'image/jpeg',bytes:10,url:'https://example.com/result.jpg',sourceUrl:'https://example.com/result.jpg',source:'ai-edit',tags:[],candidate:false,metadata:{},createdAt:'2026-10-05',updatedAt:'2026-10-05',usages:[],status:'ready'}
let container:HTMLDivElement,root:Root
async function render(component:Parameters<Root['render']>[0]){await act(async()=>root.render(component))}
async function click(label:string){await act(async()=>{const button=[...container.querySelectorAll('button')].find(item=>item.textContent===label);if(!button)throw new Error('Missing '+label);button.click()})}
beforeEach(()=>{vi.clearAllMocks();vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);vi.stubGlobal('requestAnimationFrame',(fn:FrameRequestCallback)=>{fn(0);return 1});mocks.track=track;mocks.initialIds=undefined;mocks.initialAssetUrl=undefined;mocks.restored=undefined;mocks.update.mockResolvedValue(true);vi.mocked(loadResourceLibrary).mockResolvedValue({revision:'1',assets:[],jobs:[]});container=document.createElement('div');document.body.append(container);root=createRoot(container)})
afterEach(async()=>{await act(async()=>root.unmount());container.remove();vi.unstubAllGlobals()})

describe('resource usage integration',()=>{
 it('opens a separate resource page while preserving selected point and detail scroll',async()=>{await render(createElement(TrackPanel));await click('选择点位');const panel=container.querySelector<HTMLElement>('.trk')!;panel.scrollTop=420;await click('资源库');expect(container.querySelector('[aria-label="独立资源页"]')).not.toBeNull();expect(container.querySelector('[data-testid="overview"]')!.closest('[hidden]')).not.toBeNull();await click('返回轨迹');expect(container.textContent).toContain('已选点位');expect(panel.scrollTop).toBe(420)})
 it('passes the original selected photo to the beautification page and returns from video',async()=>{await render(createElement(TrackPanel));await click('美化原照片');expect(mocks.initialAssetUrl).toBe('https://example.com/photo.jpg');expect(container.querySelector('[aria-label="独立创作页"]')!.closest('[hidden]')).toBeNull();await click('填写草稿');await click('进入创作视频');expect(container.querySelector('[aria-label="独立创作页"]')!.closest('[hidden]')).not.toBeNull();await click('返回资源库视频');expect(container.textContent).toContain('已填写草稿');expect(container.querySelector('[aria-label="独立创作页"]')!.closest('[hidden]')).toBeNull()})
 it('keeps composer draft mounted through history and restores the chosen result configuration',async()=>{await render(createElement(TrackPanel));await click('资源库');await click('选择图片创作');expect(mocks.initialIds).toEqual(['photo']);await click('填写草稿');await click('创作历史');expect(container.querySelector('[aria-label="独立创作页"]')!.closest('[hidden]')).not.toBeNull();await click('返回历史来源');expect(container.textContent).toContain('已填写草稿');await click('创作历史');await click('点击生成图恢复');expect(mocks.restored).toEqual(expect.objectContaining({job:expect.objectContaining({id:'job'}),resultAssetId:'result'}));expect(container.textContent).toContain('已填写草稿')})
 it('enters task history from the library and restores into a separate composer',async()=>{await render(createElement(TrackPanel));await click('资源库');await click('资源历史');await click('点击生成图恢复');expect(container.querySelector('[aria-label="独立创作页"]')!.closest('[hidden]')).toBeNull();expect(mocks.restored.job.prompt).toBe('原始提示词')})
 it('appends an adopted photo without overwriting originals or duplicating it',async()=>{const onSaved=vi.fn();await render(createElement(ResourceUseDialog,{track,asset,onClose:vi.fn(),onSaved}));await act(async()=>{const select=container.querySelector('select')!;select.value='point';select.dispatchEvent(new Event('change',{bubbles:true}))});await click('添加照片');expect(mocks.update).toHaveBeenCalledWith('point',{images:['https://example.com/original.jpg',asset.sourceUrl]});expect(onSaved).toHaveBeenCalledOnce();expect(appendedResourcePhotos(['https://example.com/original.jpg'], 'https://example.com/original.jpg')).toHaveLength(1)})
 it('blocks oversized point galleries and non-image source URLs',()=>{expect(()=>appendedResourcePhotos(Array.from({length:30},(_,i)=>`https://example.com/${i}.jpg`),'https://example.com/new.jpg')).toThrow('30');expect(()=>appendedResourcePhotos([],'javascript:alert(1)')).toThrow('可用点位图片')})
 it('reads resource images only on request and excludes unadopted AI results',async()=>{const onChoose=vi.fn();vi.mocked(loadResourceLibrary).mockResolvedValue({revision:'1',jobs:[],assets:[asset,{...asset,id:'candidate',candidate:true},{...asset,id:'clip',kind:'video'}]});await render(createElement(VideoResourceImagePicker,{trackId:track.id,disabled:false,onChoose}));expect(loadResourceLibrary).not.toHaveBeenCalled();await click('从资源库选择图片');expect(container.querySelectorAll('[aria-label^="使用资源图片"]')).toHaveLength(1);await click('使用');expect(onChoose).toHaveBeenCalledWith(asset.sourceUrl)})
 it('exposes selected audio and video for preview without downloading them on entry',async()=>{vi.mocked(loadResourceLibrary).mockResolvedValue({revision:'1',jobs:[],assets:[{...asset,id:'clip',kind:'video',videoRole:'travel-video'},{...asset,id:'sound',kind:'audio',videoRole:'ambient'},{...asset,id:'notchosen',kind:'audio'},{...asset,id:'draft',candidate:true,videoRole:'image-insert'}]});await render(createElement(VideoResourceSelections,{trackId:track.id,trackName:track.name}));expect(container.textContent).toContain('2 项');expect(container.querySelector('video')).toBeNull();await act(async()=>{const details=container.querySelector('details')!;details.open=true;details.dispatchEvent(new Event('toggle',{bubbles:true}))});expect(container.querySelector('video')?.getAttribute('preload')).toBe('none');expect(container.querySelector('audio')?.getAttribute('preload')).toBe('none');expect(container.textContent).toContain('尚未进入合成时间轴')})
})
