/** GeoMotion-style application chrome: compact tools and continuous data panels. */
export const TRACK_PANEL_CSS = `
.trk{font-size:var(--trk-ui-font-size)}
.trk-wrap{max-width:none;padding:0 12px 20px;margin:0 auto}
.trk-head{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:10px 12px;margin:0 -12px 12px;border-bottom:1px solid var(--trk-border);background:var(--trk-surface)}
.trk-heading{display:flex;align-items:center;gap:8px;min-width:0}.trk-heading>div{min-width:0}.trk-heading-line{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.trk-head h1{margin:0;font-size:17px;font-weight:650;letter-spacing:normal;line-height:1.35}.trk-heading .trk-muted{margin-top:2px;font-size:11px;overflow-wrap:anywhere}
.trk-app-icon,.trk-row-icon,.trk-import-icon{display:grid;place-items:center;flex-shrink:0;color:var(--trk-accent)}.trk-app-icon{width:30px;height:30px;border:1px solid var(--trk-border);border-radius:5px;background:var(--trk-hover)}.trk-app-icon svg{width:20px;height:20px}.trk-page-label{font-size:11px;color:var(--trk-muted);padding:2px 6px;border:1px solid var(--trk-border);border-radius:4px;background:var(--trk-bg)}
.trk-head-actions{justify-content:flex-end;gap:6px;flex-shrink:0}.trk-head-actions>button,.trk-detail-actions>button,.trk-more>summary{min-height:var(--trk-control-height);display:inline-flex;justify-content:center;align-items:center;gap:6px}.trk-head-actions svg,.trk-detail-actions svg{flex-shrink:0;width:16px;height:16px}
.trk-muted{font-size:var(--trk-ui-label-size);line-height:1.6}.trk-secondary,.trk-primary,.trk-danger{transition:background-color 120ms ease,border-color 120ms ease}.trk-error,.trk-progress{padding:8px 10px;font-size:var(--trk-ui-label-size);margin-bottom:10px}
.trk-drop{display:flex;flex-direction:column;align-items:center;justify-content:center;gap:12px;padding:24px 16px;margin-bottom:12px;border:1px dashed var(--trk-border);border-radius:6px;background:var(--trk-surface)}.trk-import-icon{width:34px;height:34px;border-radius:5px;background:var(--trk-hover)}.trk-import-icon svg{width:20px;height:20px}.trk-drop-copy{display:flex;flex-direction:column;gap:3px;min-width:0}.trk-drop-copy>strong{font-size:13px}.trk-drop-compact{flex-direction:row;justify-content:flex-start;padding:12px;gap:10px;text-align:left}.trk-drop-compact .trk-drop-copy{flex:1}.trk-drop-compact>button{flex-shrink:0}.trk-drop.trk-dropping{border-color:var(--trk-accent);background:var(--trk-active)}
.trk-library{margin-top:14px}.trk-library-toolbar{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:8px;min-height:36px}.trk-library-title{display:flex;align-items:baseline;gap:8px;flex-shrink:0}.trk-library-title h2{font-size:13px;font-weight:650;margin:0}.trk-library-title .trk-muted{font-size:11px}.trk-library-controls{display:flex;align-items:center;gap:8px;min-width:0}.trk-search{display:flex;align-items:center;gap:6px;padding:0 8px;min-height:var(--trk-control-height);width:min(300px,100%);border:1px solid var(--trk-border);border-radius:5px;background:var(--trk-surface);color:var(--trk-muted)}.trk-search:focus-within{outline:2px solid var(--trk-focus);outline-offset:2px}.trk-search svg{flex-shrink:0;width:15px;height:15px}.trk-search input{border:0;outline:0;background:transparent;color:var(--trk-text);min-width:0;width:100%;padding:4px 0;font-size:12px;min-height:30px}.trk-search input:focus-visible{outline:0}.trk-search input::placeholder{color:var(--trk-muted)}.trk-sort{display:flex;align-items:center;gap:6px;color:var(--trk-muted);font-size:12px;flex-shrink:0}.trk-sort select{font:inherit;min-height:var(--trk-control-height);padding:4px 7px;border:1px solid var(--trk-border);border-radius:5px;background:var(--trk-surface);color:var(--trk-text)}
.trk-sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip-path:inset(50%);white-space:nowrap;border:0}
.trk-list{display:grid;gap:0;border:1px solid var(--trk-border);border-radius:6px;overflow:hidden;background:var(--trk-surface)}.trk-row{display:flex;align-items:center;padding:0;gap:6px;border:0;border-top:1px solid var(--trk-border);border-radius:0;background:var(--trk-surface);min-width:0}.trk-row:first-child{border-top:0}.trk-row:hover,.trk-row:focus-within{background:var(--trk-hover)}.trk-row-open{display:grid;grid-template-columns:28px minmax(0,1fr) auto 16px;justify-content:start;gap:12px;padding:10px 12px;border-radius:0;min-height:68px;background:transparent}.trk-row-open:hover{background:var(--trk-hover)}.trk-row-open>svg{color:var(--trk-muted);flex-shrink:0;width:16px}.trk-row-icon{width:28px;height:28px;border-radius:5px;background:var(--trk-hover)}.trk-row-icon svg{width:19px;height:19px}.trk-row-main{min-width:0}.trk-row-title{display:flex;align-items:center;flex-wrap:wrap;gap:6px;margin-bottom:3px}.trk-row-main strong{font-size:13px;margin:0;font-weight:600}.trk-row-main>small{display:block;color:var(--trk-muted);font-size:11px;line-height:1.5;overflow-wrap:anywhere}.trk-file-type{font-size:10px;font-weight:600;color:var(--trk-muted);border:1px solid var(--trk-border);border-radius:3px;padding:1px 4px}.trk-row-stats{display:flex;flex-wrap:nowrap;gap:20px;font-variant-numeric:tabular-nums}.trk-row-stats>span{display:flex;flex-direction:column;gap:2px;min-width:72px}.trk-row-stats small{font-size:11px;color:var(--trk-muted)}.trk-row-stats strong{font-size:12px;font-weight:600;color:var(--trk-text)}.trk .trk-row-delete{background:transparent;border-color:transparent;color:var(--trk-muted);padding:4px 8px;margin-right:8px;min-height:32px}.trk .trk-row-delete:hover{color:var(--trk-danger);background:var(--trk-danger-bg);border-color:var(--trk-danger-border)}
.trk-empty{padding:24px 16px;text-align:center;display:flex;align-items:center;flex-direction:column;gap:8px;font-size:12px;border-radius:6px}.trk-empty>strong{font-size:14px;color:var(--trk-text)}.trk-empty>.trk-secondary{margin-top:4px}
.trk-detail-head{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:10px 12px;margin-bottom:0;border:1px solid var(--trk-border);border-radius:6px 6px 0 0;background:var(--trk-surface)}.trk-detail-head>div:first-child{min-width:0}.trk-detail-head h2{font-size:16px;margin:0 0 3px;line-height:1.4;overflow-wrap:anywhere}.trk-detail-head p{overflow-wrap:anywhere;font-size:11px}.trk-detail-actions{align-items:center;justify-content:flex-end;gap:6px;flex-shrink:0}.trk-more{position:relative}.trk-more>summary{list-style:none;cursor:pointer}.trk-more>summary::-webkit-details-marker{display:none}.trk-more[open]>summary{background:var(--trk-active)}.trk-more-actions{position:absolute;top:calc(100% + 5px);right:0;z-index:10;min-width:180px;padding:5px;border:1px solid var(--trk-border);border-radius:6px;background:var(--trk-surface);box-shadow:0 5px 18px var(--trk-shadow);display:grid;gap:2px}.trk-more-actions>button,.trk-more-actions>a{justify-content:flex-start;text-align:left;border:0;background:transparent;padding:5px 8px;min-height:var(--trk-control-height);font-size:12px}.trk-more-actions>.trk-danger{color:var(--trk-danger);border-top:1px solid var(--trk-border);border-radius:0 0 4px 4px}.trk-more-actions>.trk-danger:hover{background:var(--trk-danger-bg)}.trk-more-actions>.trk-secondary:hover{background:var(--trk-hover)}
.trk-stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(105px,1fr));gap:1px;padding:0;border:1px solid var(--trk-border);border-radius:6px;overflow:hidden;background:var(--trk-border);margin-bottom:12px}.trk-detail-head+.trk-stats{border-top:0;border-radius:0 0 6px 6px}.trk-stat{border:0;border-radius:0;padding:9px 12px;background:var(--trk-surface);min-width:0}.trk-stat small{display:block;font-size:11px;color:var(--trk-muted);margin-bottom:3px}.trk-stat strong{font-size:14px;font-weight:600;font-variant-numeric:tabular-nums;overflow-wrap:anywhere}
.trk-chart{border-radius:6px;padding:6px;height:220px}.trk-stage{border-radius:6px;margin-bottom:12px}.trk-note{border-radius:5px;font-size:11px;padding:6px 8px}.trk-maptitle{font-size:11px;padding:5px 8px}
.trk-delete-dialog{padding:18px;border-radius:8px}.trk-delete-dialog h2{font-size:16px}.trk-delete-dialog p{font-size:13px;line-height:1.6}.trk-delete-actions{gap:8px;margin-top:16px}
.trk-analysis{margin-bottom:12px;border:1px solid var(--trk-border);border-radius:6px;background:var(--trk-surface);color:var(--trk-text);font-size:var(--trk-ui-font-size);padding:10px}.trk-analysis>summary{cursor:pointer;min-height:32px;font-size:12px;font-weight:600}.trk-analysis>.trk-stats{margin-top:8px}.trk-analysis-guidance{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px;font-size:12px}.trk-analysis li{line-height:1.6}
@container(max-width:1050px){.trk-detail-head{flex-wrap:wrap;gap:8px}.trk-detail-actions{justify-content:flex-start;flex-wrap:wrap}.trk-row-stats{gap:12px}.trk-stats{grid-template-columns:repeat(4,minmax(0,1fr))}.trk-stat:last-child{grid-column:auto}}
@container(max-width:750px){.trk-wrap{--trk-control-height:44px;--trk-input-height:40px;padding:0 8px 16px}.trk-head{align-items:stretch;flex-direction:column;gap:8px;padding:10px 8px;margin:0 -8px 10px}.trk-head-actions{justify-content:flex-start;gap:6px}.trk-head-actions>button,.trk-detail-actions>button,.trk-more>summary{min-height:44px}.trk-drop-compact{flex-wrap:wrap;padding:10px;gap:8px}.trk-drop-compact .trk-drop-copy{min-width:160px}.trk-drop-compact>button{margin-left:42px}.trk-library-toolbar{align-items:stretch;flex-direction:column;gap:8px}.trk-library-controls{flex-wrap:wrap;gap:6px}.trk-search{flex:1;min-width:150px;width:auto;min-height:44px}.trk-search input{min-height:40px}.trk-sort>span{display:none}.trk-sort select{min-height:44px}.trk-row{gap:0}.trk-row-open{grid-template-columns:24px minmax(0,1fr) 16px;gap:8px;padding:10px 8px;min-height:44px}.trk-row-icon{width:24px;height:24px}.trk-row-open>svg{grid-column:3;grid-row:1}.trk-row-stats{grid-column:1/-1;grid-row:2;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;white-space:normal}.trk-row-stats>span{min-width:0}.trk-row-stats strong{font-size:11px;line-height:1.45}.trk .trk-row-delete{min-height:44px;margin-right:4px;padding:4px 6px}.trk-stats{grid-template-columns:repeat(2,minmax(0,1fr))}.trk-stat:last-child{grid-column:span 2}.trk-detail-head{align-items:stretch;flex-direction:column;padding:10px;gap:8px}.trk-detail-actions{gap:6px;position:relative}.trk-more{position:static}.trk-more-actions{right:0;left:auto;top:calc(100% + 5px);max-width:100%}.trk-more-actions>button,.trk-more-actions>a{min-height:44px}.trk-analysis>summary{min-height:44px}}
@media(prefers-reduced-motion:reduce){.trk-secondary,.trk-primary,.trk-danger{transition:none}}
`
