export const VIDEO_WORKSPACE_CSS = `
.trk-video-workspace{min-width:0;color:var(--trk-text);font-size:var(--trk-ui-font-size,13px)}.trk-video-workspace [hidden]{display:none!important}
.trk-video-navigation{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:6px 10px;border:1px solid var(--trk-border);border-bottom:0;background:var(--trk-surface);border-radius:var(--trk-radius-md,6px) var(--trk-radius-md,6px) 0 0;flex-wrap:wrap;min-height:36px}
.trk-video-navigation nav,.trk-video-scenes{display:flex;align-items:center;gap:6px;flex-wrap:wrap;min-width:0}
.trk-video-navigation [role=tab],.trk-video-scenes button{min-height:var(--trk-control-height,32px);min-width:60px;max-width:100%;padding:4px 10px;border:1px solid transparent;border-radius:var(--trk-radius-sm,5px);color:var(--trk-muted);background:transparent;font:inherit;font-size:var(--trk-ui-label-size,12px);line-height:1.4;white-space:normal;overflow-wrap:anywhere;cursor:pointer}
.trk-video-navigation [role=tab][aria-selected=true],.trk-video-scenes button[aria-pressed=true]{background:var(--trk-active);color:var(--trk-accent);border-color:var(--trk-border);font-weight:600}
.trk-video-navigation button:focus-visible,.trk-video-scenes button:focus-visible{outline:2px solid var(--trk-focus);outline-offset:2px}
.trk-video-scenes{padding:6px 10px;border:1px solid var(--trk-border);border-bottom:0;background:var(--trk-surface);font-size:var(--trk-ui-label-size,12px)}.trk-video-scenes>span{color:var(--trk-muted);margin-right:4px}
.trk-video-workspace button:disabled{cursor:not-allowed;opacity:.5}
.trk-video-shot-scope{display:flex;align-items:center;gap:8px;flex-wrap:wrap;padding:6px 10px;background:var(--trk-surface);border:1px solid var(--trk-border);border-bottom:0;font-size:var(--trk-ui-label-size,12px)}.trk-video-shot-scope button{min-height:var(--trk-control-height,32px);max-width:100%;padding:4px 9px;border:1px solid var(--trk-border);border-radius:var(--trk-radius-sm,5px);background:var(--trk-surface);color:var(--trk-text);font:inherit;cursor:pointer}.trk-video-shot-scope button:focus-visible{outline:2px solid var(--trk-focus);outline-offset:2px}
@container(max-width:720px){.trk-video-navigation nav,.trk-video-scenes{gap:8px}.trk-video-navigation [role=tab],.trk-video-scenes button,.trk-video-shot-scope button{min-height:44px}.trk-video-navigation [role=tab]{min-width:0;padding:6px 9px}}
`
